entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ':443'

providers:
  docker:
    network: web
    exposedByDefault: false
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.bountiful.land`)
  file:
    directory: /etc/traefik/dynamic

api:
  dashboard: true

log:
  level: ERROR
  filePath: '/logs/traefik.log'

accessLog:
  filePath: '/logs/access.log'
  bufferingSize: 100
  filters:
    statusCodes:
      - '400-499'
