http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middleware-secure-headers

    chain-basic-auth:
      chain:
        middlewares:
          - middleware-rate-limit
          - middleware-secure-headers
          - middleware-basic-auth
