http:
  routers:
    traefik:
      rule: 'PathPrefix(`/api`) || PathPrefix(`/dashboard`)'
      priority: 100
      entryPoints:
        - https
      middlewares:
        - chain-no-auth@file
      service: api@internal
      tls:
        domains:
          - main: 'bountiful.land'
            sans:
              - '*.bountiful.land'

    nginx:
      rule: 'PathPrefix(`/community`)'
      entryPoints:
        - https
      middlewares:
        - middleware-strip-prefix
        - chain-no-auth@file
      service: nginx-svc
      tls: {}
    
  services:
    nginx-svc:
      loadBalancer:
        servers:
          - url: 'http://nginx:80'
